// This file is auto-generated by @hey-api/openapi-ts

export type BodyProcessImageApiV1ProcessImagePost = {
    file?: Blob | File;
    aspect_ratio?: string;
    zoom?: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ProcessImageApiV1ProcessImagePostData = {
    body?: BodyProcessImageApiV1ProcessImagePost;
    path?: never;
    query?: never;
    url: '/api/v1/process-image';
};

export type ProcessImageApiV1ProcessImagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessImageApiV1ProcessImagePostError = ProcessImageApiV1ProcessImagePostErrors[keyof ProcessImageApiV1ProcessImagePostErrors];

export type ProcessImageApiV1ProcessImagePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};